import { join } from 'node:path';
import { readJSON, writeJSON, writeText, exists } from './util.js';

export const stateDir = (cwd) => join(cwd, '.agentsmd');
export const statePath = (cwd) => join(stateDir(cwd), 'state.json');
export const planPath = (cwd) => join(stateDir(cwd), 'BUILD_PLAN.md');

export function loadState(cwd) {
  const p = statePath(cwd);
  return exists(p) ? readJSON(p) : null;
}

export function saveState(cwd, state) {
  writeJSON(statePath(cwd), state);
  writeText(planPath(cwd), renderPlan(state));
}

export function progress(state) {
  const done = state.steps.filter((s) => s.status === 'completed').length;
  return { done, total: state.steps.length };
}

export function renderPlan(state) {
  const { done, total } = progress(state);
  const lines = [
    `# Build Plan — ${state.goal}`,
    '',
    `**Recipe:** \`${state.recipe}\`  ·  **Progress:** ${done}/${total}`,
    '',
    '> Generated by agentsmd. `agentsmd run` reads `.agentsmd/state.json`.',
    '> Edit the state file if you want to customize steps.',
    '',
    '## Steps',
  ];
  state.steps.forEach((s, i) => {
    const box = s.status === 'completed' ? 'x' : ' ';
    const cur = i === state.current && s.status !== 'completed' ? '  ← current' : '';
    const skipped = s.skipped ? ' _(skipped)_' : '';
    lines.push(`- [${box}] ${i + 1}. ${s.title}${cur}${skipped}`);
    if (s.check) lines.push(`      - verify: \`${s.check}\``);
  });
  lines.push('');
  return lines.join('\n');
}
