function bullets(arr) {
  const items = arr && arr.length ? arr : ['(none yet)'];
  return items.map((x) => `- ${x}`).join('\n');
}

function commandsBlock(cmds) {
  if (!cmds || !Object.keys(cmds).length) return '_(none specified)_';
  return Object.entries(cmds)
    .map(([k, v]) => `- \`${k}\`: \`${v}\``)
    .join('\n');
}

export function renderAgents(p) {
  return `# AGENTS.md

> Generated by agentsmd from \`agentsmd.config.json\` (single source of truth).
> Do not edit by hand — edit the config and run \`agentsmd gen\`.

## Project
**${p.name}** — ${p.oneLiner || ''}

## Tech stack
${bullets(p.stack)}

Package manager: \`${p.packageManager || 'npm'}\`

## Commands
${commandsBlock(p.commands)}

## Conventions
${bullets(p.conventions)}

## Do NOT
${bullets(p.doNot)}

## Security
${bullets(p.security)}

## Tool decisions
- Before adopting a new external tool or library, run \`agentsmd capabilities search "<goal>" --json\` and review the matching card's risks, verification notes, and verified date.
- Treat cards marked stale as leads to re-check against the upstream source, not as current facts.

## Definition of done (review before finishing a task)
${bullets(p.reviewCriteria)}

## Current priorities
${bullets(p.priorities)}
`;
}

export function agentsBody(p) {
  // AGENTS.md without the top H1, for embedding in other targets.
  return renderAgents(p).split('\n').slice(1).join('\n').trimStart();
}
