import { agentsBody } from './agents.js';

export function renderCursor(p) {
  return `---
description: Project rules for ${p.name} (generated by agentsmd)
globs:
alwaysApply: true
---

${agentsBody(p)}`;
}
